Update the sql generation in the application.properties
Access-Point-Program/cohort-3-simulation-runner pull request #90
Opened 2023-12-19 22:06 UTC by jgarner76

## Done Criteria Pull Request

## Issue #18

## Acceptance Criteria
- [ ] Meets all predetermined requirements
- [ ] Team is satisfied with the result
- [ ] There has been a second set of eyes for review
- [ ] Story process, vision, and result have been documented well enough that other teams are able to understand
- [ ] Unnecessary code has been cleaned
- [ ] Code has been unit tested
- [ ] Product can be translated across platforms (multiple devices/laptops can access)

2023-12-20 14:44 UTC, chris-marfia requested changes

2023-12-20 14:45 UTC, chris-marfia commented
@Access-Point-Program/hocus-pocus Please work together to get this PR reviewed, corrected, and merged this morning.

2023-12-20 21:26 UTC, calisward approved these changes

2023-12-20 21:27 UTC, chris-marfia commented on src/main/java/com/HocusPocus/Simulation/simulationDb/SimulationResults.java
> +//Hi
```suggestion
```

2023-12-21 15:20 UTC, jgarner76 reviewed
It looks good

2023-12-21 15:41 UTC, chris-marfia approved these changes

2023-12-21 15:51 UTC, merged